/* Generated by wayland-scanner 1.24.0, modified for dragengine */

/*
 * Copyright © 2022 Kenny Levinsen
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <dragengine/dragengine_configuration.h>
#if defined(OS_UNIX_X11) && defined(OS_UNIX_WAYLAND)

#include "wayland-defs.h"


// Wayland EGL
////////////////

deWlDynLib deWaylandEglLib("OpenGL-WL", "wayland-egl", 1);

deWlDynLibFunc<wl_egl_window*(const wl_surface*, int, int)> deoglWlEglWindowCreate(deWaylandEglLib, "wl_egl_window_create");
deWlDynLibFunc<void(wl_egl_window*)> deoglWlEglWindowDestroy(deWaylandEglLib, "wl_egl_window_destroy");
deWlDynLibFunc<void(wl_egl_window*, int, int, int, int)> deoglWlEglWindowResize(deWaylandEglLib, "wl_egl_window_resize");


#endif
