from SConsCommon import *

Import( 'parent_env parent_targets parent_report' )

envModule = parent_env.Clone()

buildModule = envModule[ 'build_image_jpeg' ] != TernaryVariableNo
parent_report[ 'build JPEG Image Module' ] = 'yes' if buildModule else 'no'

if not buildModule:
	Return()

libs = []
appendLibrary( envModule, parent_targets[ 'dragengine' ], libs )
appendLibrary( envModule, parent_targets[ 'lib_libjpeg' ], libs )

envModule.Append( CPPFLAGS = parent_env[ 'MODULE_CPPFLAGS' ] )
envModule.Append( LINKFLAGS = parent_env[ 'MODULE_LINKFLAGS' ] )

# fetch values in expanded form for later use
versionMajor = 1
versionMinor = 0
versionString = '{}.{}'.format( versionMajor, versionMinor )

pathConfig = '{}/modules/image/jpeg/{}'.format( envModule.subst( envModule[ 'path_de_config' ] ), versionString )
pathModule = '{}/modules/image/jpeg/{}'.format( envModule.subst( envModule[ 'path_de_data' ] ), versionString )

# setup the builders
sources = []
headers = []
globFiles( envModule, 'src', '*.cpp', sources )
globFiles( envModule, 'src', '*.h', headers )

objects = [ envModule.SharedObject( s ) for s in sources ]

library = envModule.SharedLibrary( target='imgjpeg', source=objects, LIBS=libs )
targetBuild = envModule.Alias( 'img_jpeg_build', library )

install = []
archive = {}
for l in library:
	if l.name.endswith( envModule[ 'SHLIBSUFFIX' ] ):
		install.append( envModule.Install( pathModule, l ) )
		archive[ os.path.join( pathModule, l.name ) ] = l

manifestUpdates = [
	{ 'action': 'filename', 'name': library[ 0 ].name, 'keyword': 'FILENAME' },
	{ 'action': 'filesize', 'path': library[ 0 ].abspath, 'keyword': 'FILESIZE' },
	{ 'action': 'filehash', 'path': library[ 0 ].abspath, 'keyword': 'SHA1SUM' },
	{'action': 'version', 'version': '1.0', 'keyword': 'VERSION'}]

for l in reversed( parent_targets[ 'lib_libjpeg' ][ 'runtimelibs' ] ):
	manifestUpdates.append( { 'action': 'preloadLibrary', 'path': l.name } )
	install.append( envModule.Install( pathModule, l ) )
	archive[ os.path.join( pathModule, l.name ) ] = l

manifest = envModule.File( 'src/module.xml' )
updateManifest = envModule.Command( manifest, manifest.srcnode(),
	Action( UpdateModuleManifest ), ManifestUpdates=manifestUpdates )
Depends( updateManifest, library )
Depends( updateManifest, parent_targets[ 'lib_libjpeg' ][ 'runtimelibs' ] )

install.append( envModule.Install( pathModule, updateManifest ) )
archive[ os.path.join( pathModule, 'module.xml' ) ] = updateManifest[ 0 ]

targetInstall = envModule.Alias( 'img_jpeg', install )

# source directory required for special commands
srcdir = Dir( '.' ).srcnode().abspath

# cloc
buildClocBare = BuildCLOC( envModule, [ '{}/src'.format( srcdir ) ], '{}/clocreport.csv'.format( srcdir ), [ 'doc' ] )
Depends( buildClocBare, sources )
Depends( buildClocBare, headers )
buildCloc = envModule.Alias( 'img_jpeg_cloc', buildClocBare )

# add the targets to the targets list
parent_targets[ 'img_jpeg' ] = {
	'name' : 'JPEG Image Module',
	'build' : targetBuild,
	'install' : targetInstall,
	'archive-engine' : archive,
	'cloc' : buildCloc,
	'clocReport' : '{}/clocreport.csv'.format( srcdir ) }
