title: Drag[en]gine Game Engine
email: info@dragondreams.ch
description: >-
  Documentation for the Drag[en]gine Game Engine.
domain: "lordofdragons.github.io"
url: "https://lordofdragons.github.io"
baseurl: "/dragengine"
twitter_username: DragonDreamsGD
github_username: LordOfDragons
repository: LordOfDragons/dragengine-doc

# Build settings
remote_theme: just-the-docs/just-the-docs@v0.5.2
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

nav_external_links:
  - title: Home Page
    url: https://dragondreams.ch/index.php/dragengine
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

keep_files:
  - artifacts

callouts:
  highlight:
    color: yellow
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: blue
  