#!/bin/sh

set -e

case "$1" in
   configure)
      if ! [ $(getent group games ) ]; then
          groupadd --quiet games
      fi

      if ! [ -d /opt/delauncher/games ]; then
          mkdir -p /opt/delauncher/games
          chgrp games /opt/delauncher /opt/delauncher/games
          chmod 775 /opt/delauncher /opt/delauncher/games
      fi
      ;;
esac

#DEBHELPER#

exit 0
