#!/bin/sh

#DEBHELPER#

set -e

if [ "$1" == configure ]; then
	# /usr/share/games/delauncher/games is only created not removed since
	# it contains user installed games and should NOT be deleted if this
	# package is uninstalled

	if ! [ -d /usr/share/games ]; then
		mkdir /usr/share/games
		chown 755 /usr/share/games
	fi

	if ! [ -d /usr/share/games/delauncher ]; then
		mkdir /usr/share/games/delauncher/games
		chgrp games /usr/share/games/delauncher
		chown 2775 /usr/share/games/delauncher
	fi

	if ! [ -d /usr/share/games/delauncher/games ]; then
		mkdir /usr/share/games/delauncher/games
		chgrp games /usr/share/games/delauncher/games
		chown 2775 /usr/share/games/delauncher/games
	fi
fi

