$Directories = @(
    '%ARCH%',
    'demodules\%ARCH%',
    'dragengine\%ARCH%',
    'enginedeal\%ARCH%',
    'extern\denetwork\%ARCH%',
    'extern\deremotelauncher\%ARCH%',
    'extern\dragonscript\%ARCH%',
    'extern\eossdk\%ARCH%',
    'extern\freetype\%ARCH%',
    'extern\fox\%ARCH%',
    'extern\libjpeg\%ARCH%',
    'extern\libogg\%ARCH%',
    'extern\libpng\%ARCH%',
    'extern\libsharpyuv\%ARCH%',
    'extern\libtheora\%ARCH%',
    'extern\libvorbis\%ARCH%',
    'extern\libvorbisfile\%ARCH%',
    'extern\libvpx\%ARCH%',
    'extern\libwebm\%ARCH%',
    'extern\libwebp\%ARCH%',
    'extern\libwebpdemux\%ARCH%',
    'extern\modio\%ARCH%',
    'extern\openal\%ARCH%',
    'extern\openxr\%ARCH%',
    'extern\soundtouch\%ARCH%',
    'extern\steamsdk\%ARCH%',
    'extern\zlib\%ARCH%',
    'extern\soundtouch\%ARCH%',
    'igde\editors\animator\%ARCH%',
    'igde\editors\conversation\%ARCH%',
    'igde\editors\font\%ARCH%',
    'igde\editors\gamedefinition\%ARCH%',
    'igde\editors\langpack\%ARCH%',
    'igde\editors\particleemitter\%ARCH%',
    'igde\editors\project\%ARCH%',
    'igde\editors\project_testrunner\%ARCH%',
    'igde\editors\rig\%ARCH%',
    'igde\editors\skin\%ARCH%',
    'igde\editors\sky\%ARCH%',
    'igde\editors\speechanimation\%ARCH%',
    'igde\editors\synthesizer\%ARCH%',
    'igde\editors\world\%ARCH%',
    'igde\igde\%ARCH%',
    'igde\shared\%ARCH%',
    'launcher\console\%ARCH%',
    'launcher\gui\%ARCH%',
    'launcher\gui_engine\%ARCH%',
    'launcher\live\%ARCH%',
    'launcher\shared\%ARCH%',
    'launcher\gui_engine\%ARCH%',
    'modules\ai\deai\%ARCH%',
    'modules\animation\deanim\%ARCH%',
    'modules\animator\deanimator\%ARCH%',
    'modules\archive\delga\%ARCH%',
    'modules\audio\audnull\%ARCH%',
    'modules\audio\openal\%ARCH%',
    'modules\combined\fbx\animation\%ARCH%',
    'modules\combined\fbx\model\%ARCH%',
    'modules\combined\fbx\rig\%ARCH%',
    'modules\combined\fbx\skin\%ARCH%',
    'modules\crashrecovery\basicrecovery\%ARCH%',
    'modules\crashrecovery\simplyquit\%ARCH%',
    'modules\font\defont\%ARCH%',
    'modules\font\freetype\%ARCH%',
    'modules\graphic\null\%ARCH%',
    'modules\graphic\opengl\%ARCH%',
    'modules\image\ies\%ARCH%',
    'modules\image\jpeg\%ARCH%',
    'modules\image\png\%ARCH%',
    'modules\image\png3d\%ARCH%',
    'modules\image\tga\%ARCH%',
    'modules\image\webp\%ARCH%',
    'modules\image\webp3d\%ARCH%',
    'modules\input\w32input\%ARCH%',
    'modules\langpack\delangpack\%ARCH%',
    'modules\model\demodel\%ARCH%',
    'modules\network\basic\%ARCH%',
    'modules\occlusionmesh\deocclusionmesh\%ARCH%',
    'modules\physics\bullet\%ARCH%',
    'modules\rig\derig\%ARCH%',
    'modules\scripting\dragonscript\%ARCH%',
    'modules\service\eossdk\%ARCH%',
    'modules\service\modio\%ARCH%',
    'modules\service\msgdk\%ARCH%',
    'modules\service\steamsdk\%ARCH%',
    'modules\skin\deskin\%ARCH%',
    'modules\sound\oggvorbis\%ARCH%',
    'modules\synthesizer\desynthesizer\%ARCH%',
    'modules\video\apng\%ARCH%',
    'modules\video\theora\%ARCH%',
    'modules\video\webm\%ARCH%',
    'modules\vr\null\%ARCH%',
    'modules\vr\openxr\%ARCH%',
    'shared\fbx\%ARCH%',
    'shared\vulkan\%ARCH%',
    'tools\blender\%ARCH%'
)

$Architectures = @(
    'x64'
)

ForEach ($Architecture in $Architectures) {
    ForEach ($Directory in $Directories) {
        $DirName = "$Directory".Replace("%ARCH%", $Architecture)
        Write-Host "Remove directory '$DirName'..."
        if (Test-Path $DirName) {
            Remove-Item -Path $DirName -Force -Recurse
        }
    }
}

if (Test-Path Distribute) {
    Remove-Item -Path Distribute -Force -Recurse
}
