from SConsCommon import *

import zipfile
import os

Import( 'parent_env parent_targets parent_report' )

envAddon = parent_env.Clone()

pathShare = envAddon.subst(envAddon['path_igde_share'])

files = []
globFiles(envAddon, 'dragengine-import-export', '*.py', files)
files.append('dragengine-import-export/blender_manifest.toml')

archiveFiles = {f:envAddon.File(f) for f in files}
def archiveZip(env, target, source):
	with zipfile.ZipFile(target[0].abspath, 'w', zipfile.ZIP_DEFLATED) as arcfile:
		for path, node in archiveFiles.items():
			arcfile.write(node.srcnode().abspath, path)

versionString = envAddon['version']
if envAddon['force_version']:
        versionString = envAddon['force_version']

# blender repository version has to be "X.Y.Z" whereas "X.Y" matches drag[en]gine
# release version and Z starts at 0 incrementally updated with each release.
# Z does not line up with potential drag[en]gine patch since blender repository
# package can be released more often if required
versionParts = [int(x) for x in versionString.split('.')]
while len(versionParts) < 3:
	versionParts.append(0)

# set custom patch version number. it is a bit annoying to handle this in the script
# hence a version based custom value is used. the version check ensures the patch
# version goes back to 0 if the drag[en]gine release version is bumped
versionParts[2] = 0

if versionParts[1] == 22:
	versionParts[2] = 1

# update manifest. done in source directly to avoid complicated copying
with open(envAddon.File('blender_manifest.toml.in').srcnode().abspath, 'r') as f:
	content = f.read().replace('{VERSION}', '.'.join([str(x) for x in versionParts]))
with open(envAddon.File('dragengine-import-export/blender_manifest.toml').srcnode().abspath, 'w') as f:
	f.write(content)

filename = '{}-{}.zip'.format(envAddon['addon_name_blender'], versionString)

targetBuild = envAddon.Command(filename, files, envAddon.Action(archiveZip, 'Archiving $TARGET'))

install = envAddon.Install(os.path.join(pathShare, 'tools'), targetBuild)
targetInstall = envAddon.Alias('blender-addon', install)

filename = os.path.join(pathShare, 'tools', filename)

archiveDevelop = {}
archiveDevelop[filename] = targetBuild[0]

parent_targets['blender-addon'] = {
	'name' : 'Drag[en]gine Blender AddOn',
	'build' : targetBuild,
	'install' : targetInstall,
	'install-igde-runtime' : targetInstall,
	'archive-igde' : archiveDevelop}
