from SConsCommon import *

import zipfile
import os

Import( 'parent_env parent_targets parent_report' )

envAddon = parent_env.Clone()

pathShare = envAddon.subst(envAddon['path_igde_share'])


versionString = envAddon['version']
if envAddon['force_version']:
        versionString = envAddon['force_version']

# blender repository version has to be "X.Y.Z" whereas "X.Y" matches drag[en]gine
# release version and Z starts at 0 incrementally updated with each release.
# Z does not line up with potential drag[en]gine patch since blender repository
# package can be released more often if required
versionParts = [int(x) for x in versionString.split('.')]
while len(versionParts) < 3:
	versionParts.append(0)

# set custom patch version number. it is a bit annoying to handle this in the script
# hence a version based custom value is used. the version check ensures the patch
# version goes back to 0 if the drag[en]gine release version is bumped
versionParts[2] = 0

if versionParts[1] == 22:
	versionParts[2] = 1

blenderVersionString = '.'.join([str(x) for x in versionParts])


addonSrcDir = 'dragengine-import-export'
addonDestDir = 'dragengine-import-export'

files = []
globFiles(envAddon, addonSrcDir, '*.py', files)
print(files)

files2 = []
for f in files:
	files2.extend(envAddon.Install(addonDestDir, envAddon.File(f).srcnode()))

def copyModifyFile(env, target, source):
	with open(source[0].abspath, 'r') as f:
		content = f.read()
	content = content.replace('{RELEASE_VERSION}', blenderVersionString)
	with open(target[0].abspath, 'w') as f:
		f.write(content)

files2.extend(envAddon.Command('{}/blender_manifest.toml'.format(addonDestDir),
	'blender_manifest.toml.in', envAddon.Action(copyModifyFile, 'Copy-Modify $TARGET')))

files2.extend(envAddon.Command('{}/de_version.py'.format(addonDestDir),
	'de_version.py.in', envAddon.Action(copyModifyFile, 'Copy-Modify $TARGET')))


buildDir = envAddon.Dir('.')

archiveFiles = {buildDir.rel_path(f): f for f in files2}
def archiveZip(env, target, source):
	with zipfile.ZipFile(target[0].abspath, 'w', zipfile.ZIP_DEFLATED) as arcfile:
		for path, node in archiveFiles.items():
			arcfile.write(node.abspath, path)

filename = '{}-{}.zip'.format(envAddon['addon_name_blender'], versionString)

targetBuild = envAddon.Command(filename, files2, envAddon.Action(archiveZip, 'Archiving $TARGET'))

install = envAddon.Install(os.path.join(pathShare, 'tools'), targetBuild)
targetInstall = envAddon.Alias('blender-addon', install)

filename = os.path.join(pathShare, 'tools', filename)

archiveDevelop = {}
archiveDevelop[filename] = targetBuild[0]

parent_targets['blender-addon'] = {
	'name' : 'Drag[en]gine Blender AddOn',
	'build' : targetBuild,
	'install' : targetInstall,
	'install-igde-runtime' : targetInstall,
	'archive-igde' : archiveDevelop}
