/*
 * MIT License
 *
 * Copyright (C) 2024, DragonDreams GmbH (info@dragondreams.ch)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef _DEPARTICLEEMITTEROFFSETS_H_
#define _DEPARTICLEEMITTEROFFSETS_H_

/**
 * \brief Particle Emitter Offsets.
 * Offset and structure size definitions for use by modules to index into the
 * deParticleEmitter::sParticle struct. These defines respect alignment
 * properties of the target platform and compiler used to compile the
 * dragengine libraries.
 */
#define DEPE_SPARTICLE_SIZE							40

#define DEPE_SPARTICLE_OFFSET_LIFETIME				0
#define DEPE_SPARTICLE_OFFSET_POSITION_X			4
#define DEPE_SPARTICLE_OFFSET_POSITION_Y			8
#define DEPE_SPARTICLE_OFFSET_POSITION_Z			12
#define DEPE_SPARTICLE_OFFSET_LINEAR_VELOCITY		16
#define DEPE_SPARTICLE_OFFSET_ANGULAR_VELOCITY		20
#define DEPE_SPARTICLE_OFFSET_CAST_SIZE				24
#define DEPE_SPARTICLE_OFFSET_CAST_EMISSIVITY		28

#define DEPE_SPARTICLE_OFFSET_LINEAR_DIRECTION_X	32
#define DEPE_SPARTICLE_OFFSET_LINEAR_DIRECTION_Y	33
#define DEPE_SPARTICLE_OFFSET_LINEAR_DIRECTION_Z	34
#define DEPE_SPARTICLE_OFFSET_ROTATION				35
#define DEPE_SPARTICLE_OFFSET_CAST_RED				36
#define DEPE_SPARTICLE_OFFSET_CAST_GREEN			37
#define DEPE_SPARTICLE_OFFSET_CAST_BLUE				38
#define DEPE_SPARTICLE_OFFSET_CAST_TRANSPARENCY		39

#define DEPE_SPARTICLE_BLOCK1_OFFSET				0
#define DEPE_SPARTICLE_BLOCK1_SIZE					16
#define DEPE_SPARTICLE_BLOCK2_OFFSET				16
#define DEPE_SPARTICLE_BLOCK2_SIZE					16
#define DEPE_SPARTICLE_BLOCK3_OFFSET				32
#define DEPE_SPARTICLE_BLOCK3_SIZE					4
#define DEPE_SPARTICLE_BLOCK4_OFFSET				36
#define DEPE_SPARTICLE_BLOCK4_SIZE					4

/*
#define DEPE_SPARTICLE_SIZE							28

#define DEPE_SPARTICLE_OFFSET_LIFETIME				0
#define DEPE_SPARTICLE_OFFSET_POSITION_X			4
#define DEPE_SPARTICLE_OFFSET_POSITION_Y			8
#define DEPE_SPARTICLE_OFFSET_POSITION_Z			12
#define DEPE_SPARTICLE_OFFSET_LINEAR_DIRECTION_X	16
#define DEPE_SPARTICLE_OFFSET_LINEAR_DIRECTION_Y	17
#define DEPE_SPARTICLE_OFFSET_LINEAR_DIRECTION_Z	18
#define DEPE_SPARTICLE_OFFSET_ANGULAR_VELOCITY		19
#define DEPE_SPARTICLE_OFFSET_LINEAR_VELOCITY		20
#define DEPE_SPARTICLE_OFFSET_ROTATION				21
#define DEPE_SPARTICLE_OFFSET_CAST_SIZE				22
#define DEPE_SPARTICLE_OFFSET_CAST_EMISSIVITY		23
#define DEPE_SPARTICLE_OFFSET_CAST_RED				24
#define DEPE_SPARTICLE_OFFSET_CAST_GREEN			25
#define DEPE_SPARTICLE_OFFSET_CAST_BLUE				26
#define DEPE_SPARTICLE_OFFSET_CAST_TRANSPARENCY		27

#define DEPE_SPARTICLE_BLOCK1_OFFSET				0
#define DEPE_SPARTICLE_BLOCK1_SIZE					16
#define DEPE_SPARTICLE_BLOCK2_OFFSET				16
#define DEPE_SPARTICLE_BLOCK2_SIZE					4
#define DEPE_SPARTICLE_BLOCK3_OFFSET				20
#define DEPE_SPARTICLE_BLOCK3_SIZE					4
#define DEPE_SPARTICLE_BLOCK4_OFFSET				24
#define DEPE_SPARTICLE_BLOCK4_SIZE					4
*/

#endif
