#ifndef EXPORTED_VULKAN_FUNCTION
	#define EXPORTED_VULKAN_FUNCTION( name )
#endif
#ifndef GLOBAL_LEVEL_VULKAN_FUNCTION
	#define GLOBAL_LEVEL_VULKAN_FUNCTION( name )
#endif
#ifndef INSTANCE_LEVEL_VULKAN_FUNCTION
	#define INSTANCE_LEVEL_VULKAN_FUNCTION( name )
#endif
#ifndef INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION
	#define INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION( name, extension )
#endif
#ifndef DEVICE_LEVEL_VULKAN_FUNCTION
	#define DEVICE_LEVEL_VULKAN_FUNCTION( name )
#endif
#ifndef DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION
	#define DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION( name, extension )
#endif


EXPORTED_VULKAN_FUNCTION( vkGetInstanceProcAddr )
EXPORTED_VULKAN_FUNCTION( vkGetDeviceProcAddr )

GLOBAL_LEVEL_VULKAN_FUNCTION( vkEnumerateInstanceExtensionProperties ) 
GLOBAL_LEVEL_VULKAN_FUNCTION( vkEnumerateInstanceLayerProperties ) 
GLOBAL_LEVEL_VULKAN_FUNCTION( vkCreateInstance )

INSTANCE_LEVEL_VULKAN_FUNCTION( vkDestroyInstance )
INSTANCE_LEVEL_VULKAN_FUNCTION( vkEnumeratePhysicalDevices )
INSTANCE_LEVEL_VULKAN_FUNCTION( vkGetPhysicalDeviceProperties )
INSTANCE_LEVEL_VULKAN_FUNCTION( vkCreateDevice )
INSTANCE_LEVEL_VULKAN_FUNCTION( vkGetPhysicalDeviceQueueFamilyProperties )

DEVICE_LEVEL_VULKAN_FUNCTION( vkDestroyDevice )
DEVICE_LEVEL_VULKAN_FUNCTION( vkGetDeviceQueue )
DEVICE_LEVEL_VULKAN_FUNCTION( vkCreateCommandPool )
DEVICE_LEVEL_VULKAN_FUNCTION( vkDestroyCommandPool )


#undef EXPORTED_VULKAN_FUNCTION
#undef GLOBAL_LEVEL_VULKAN_FUNCTION
#undef INSTANCE_LEVEL_VULKAN_FUNCTION
#undef INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION
#undef DEVICE_LEVEL_VULKAN_FUNCTION
#undef DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION
