name: Build Msix

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      artifactWindows:
        required: true
        type: string
      artifactMsix:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Install required packages
        run: sudo apt -y install scons
        
      - name: Get Archives
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactWindows }}
          path: installer/artifacts
      
      - name: Build MSIX
        working-directory: installer
        run: ./build_msix.py ${{ inputs.releaseVersion }}
        
      - name: Copy MSXI
        run: |
          cp -a installer/build_msix/dragengine-${{ inputs.releaseVersion }}.msix dragengine-${{ inputs.releaseVersion }}.msix
          cp -a installer/build_msix/deigde-${{ inputs.releaseVersion }}.msix deigde-${{ inputs.releaseVersion }}.msix
        
      - name: Store MSIX
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactMsix }}
          path: |
            dragengine-${{ inputs.releaseVersion }}.msix
            deigde-${{ inputs.releaseVersion }}.msix
          if-no-files-found: error
