name: Build Linux

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: master
      releaseVersion:
        required: true
        type: string
      buildVersion:
        required: true
        type: string
      artifactArchive:
        required: true
        type: string
      artifactInstaller:
        required: true
        type: string
      artifactTools:
        required: true
        type: string
      lfscache:
        required: false
        default: true
        type: boolean
      codeql:
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: ${{ !inputs.lfscache }}
          submodules: 'recursive'
          ref: ${{ inputs.branch }}
      
      - name: Create LFS file hash list
        if: ${{ inputs.lfscache }}
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-objects-id
      
      - name: Restore LFS Cache
        uses: actions/cache@v4
        id: lfs-cache
        if: ${{ inputs.lfscache }}
        with:
          path: .git/lfs
          key: lfs-cache-${{ hashFiles('.lfs-objects-id') }}
          restore-keys: lfs-cache-

      - name: Git LFS Pull
        if: ${{ inputs.lfscache }}
        run: |
          git lfs pull 2>&1 | tee lfs.log
          if grep -q "error:" "lfs.log" ; then
            git lfs logs last
            exit 1
          fi
      
      - name: Install required packages
        run: |
          sudo apt -y update
          sudo apt -y install build-essential scons cmake autoconf libtool nasm \
            patchelf libx11-dev libxrandr-dev libgl-dev libxi-dev libpulse-dev \
            libasound2-dev portaudio19-dev libxft-dev extra-cmake-modules \
            flex bison gettext doxygen
      
      - name: Init custom.py
        run: |
          cp ${{ github.workspace }}/.github/workflows/custom_linux.py custom.py
          sed -i -e 's/{ReleaseVersion}/${{ inputs.releaseVersion }}/g' custom.py
          sed -i -e 's/{BuildVersion}/${{ inputs.buildVersion }}/g' custom.py
      
      - name: Build external
        # Build first all external libraries. Aboids avoid running CodeQL on them.
        # CMake based projects are problem children that like to get stuck forever in CMake
        # on Ubuntu and GitHub. build them first without parallel to avoid hangups
        run: |
          scons -j 1 \
            lib_openxr \
            lib_openvr \
            lib_libjpeg \
            lib_libwebm \
            lib_modio
          scons -j 14 \
            lib_dragonscript \
            lib_fox \
            lib_libapng \
            lib_libevdev \
            lib_libogg \
            lib_libpng \
            lib_liburing \
            lib_libtheora \
            lib_libvorbis \
            lib_libvpx \
            lib_libwebp \
            lib_openal \
            lib_soundtouch \
            lib_steamsdk \
            lib_zlib
        # lib_sndio
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        if: ${{ inputs.codeql }}
        with:
          languages: c-cpp
          build-mode: manual
      
      - name: Build
        run: |
          scons -j 14 archive installer
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        if: ${{ inputs.codeql }}
        with:
          category: "/language:c-cpp"
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Store Archives
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactArchive }}
          path: |
            archive/build/dragengine-${{ inputs.releaseVersion }}-linux64.tar.bz2
            archive/build/dragengine-dev-${{ inputs.releaseVersion }}-linux64.tar.bz2
            archive/build/deigde-${{ inputs.releaseVersion }}-linux64.tar.bz2
            archive/build/deigde-dev-${{ inputs.releaseVersion }}-linux64.tar.bz2
            archive/build/despecial-${{ inputs.releaseVersion }}-linux64.tar.bz2
          if-no-files-found: error
        
      - name: Store Installers
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactInstaller }}
          path: |
            installer/build/install-dragengine-${{ inputs.releaseVersion }}-linux64.sh
            installer/build/install-dragengine-dev-${{ inputs.releaseVersion }}-linux64.sh
            installer/build/install-deigde-${{ inputs.releaseVersion }}-linux64.sh
            installer/build/install-deigde-dev-${{ inputs.releaseVersion }}-linux64.sh
          if-no-files-found: error
        
      - name: Store Tools
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactTools }}
          path: |
            src/tools/blender/build/blender-addon-dragengine-${{ inputs.buildVersion }}.zip
          if-no-files-found: error
