name: Build Linux CI

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: master
      releaseVersion:
        required: true
        type: string
      buildVersion:
        required: true
        type: string
      artifactInstaller:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'
          ref: ${{ inputs.branch }}
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons cmake autoconf libtool nasm \
            patchelf libasound2-dev extra-cmake-modules flex bison gettext
      
      - name: Init custom.py
        run: |
          cp ${{ github.workspace }}/.github/workflows/custom_linux_ci.py custom.py
          sed -i -e 's/{ReleaseVersion}/${{ inputs.releaseVersion }}/g' custom.py
          sed -i -e 's/{BuildVersion}/${{ inputs.buildVersion }}/g' custom.py
      
      - name: Build
        # certain CMake based projects are problem children that like to get stuck
        # in CMake on Ubuntu. build them first to avoid it loking up things
        run: |
          scons -j 1 lib_libjpeg
          scons -j 14 archive installer
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Store Installers
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactInstaller }}
          path: |
            installer/build/install-dragengine-ci-${{ inputs.releaseVersion }}-linux64.sh
            installer/build/install-deigde-ci-${{ inputs.releaseVersion }}-linux64.sh
          if-no-files-found: error
