name: Development Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: '9999'
      debugBuild:
        description: 'Debug build'
        required: true
        type: boolean
        default: true

jobs:
  build_windows:
    uses: ./.github/workflows/build_windows.yml
    with:
      releaseVersion: ${{ github.event.inputs.version }}
      buildVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-windows
      debugBuild: ${{ github.event.inputs.debugBuild == 'true' }}
  
  build_windows_installer:
    needs: [build_windows]
    uses: ./.github/workflows/build_windows_installer.yml
    with:
      releaseVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-windows
      artifactInstaller: installers-windows
