name: Nightly Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons cmake autoconf libtool nasm \
            patchelf libx11-dev libxrandr-dev libgl-dev libxi-dev libpulse-dev \
            libasound2-dev portaudio19-dev libxft-dev extra-cmake-modules \
            flex bison gettext
      
      - name: Init custom.py
        run: cp ${{ github.workspace }}/.github/workflows/nightly_custom.py custom.py
      
      - name: Build
        # Ubuntu keeps on hanging by using multi-threaded builds.
        # Seems to be a Python issue with Ubunutu
        #run: scons -j 14 archive installer
        run: scons -j 1 archive installer
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Upload Artifacts
          retention-days: 3
          path: |
            ${{ github.workspace }}/archive/build/dragengine-nightly-linux64.tar.bz2
            ${{ github.workspace }}/archive/build/dragengine-dev-nightly-linux64.tar.bz2
            ${{ github.workspace }}/archive/build/deigde-nightly-linux64.tar.bz2
            ${{ github.workspace }}/archive/build/deigde-dev-nightly-linux64.tar.bz2
            ${{ github.workspace }}/archive/build/despecial-nightly-linux64.tar.bz2
            ${{ github.workspace }}/installer/build/install-dragengine-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-dragengine-dev-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-deigde-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-deigde-dev-nightly-linux64.sh
