name: Nightly Build

on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons cmake autoconf libtool nasm \
            patchelf libx11-dev libxrandr-dev libgl-dev libxi-dev libpulse-dev \
            libasound2-dev portaudio19-dev libxft-dev extra-cmake-modules \
            flex bison gettext
      
      - name: Init custom.py
        run: cp ${{ github.workspace }}/.github/workflows/nightly_custom_linux.py custom.py
      
      - name: Build
        # openvr seems to be a problem child that like to get stuck in CMake on Ubuntu.
        # build it first to avoid it loking up things. libjpeg is another trouble maker.
        run: |
          scons -j 1 lib_openvr
          scons -j 1 lib_libjpeg
          scons -j 14 archive installer
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-linux
          path: |
            installer/build/install-dragengine-nightly-linux64.sh
            installer/build/install-dragengine-dev-nightly-linux64.sh
            installer/build/install-deigde-nightly-linux64.sh
            installer/build/install-deigde-dev-nightly-linux64.sh
  
  build_windows:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons cmake autoconf libtool nasm \
            patchelf libx11-dev libxrandr-dev libgl-dev libxi-dev libpulse-dev \
            libasound2-dev portaudio19-dev libxft-dev extra-cmake-modules \
            flex bison gettext mingw-w64
          sudo apt -y install --no-install-recommends unzip procps xvfb
      
      - name: Init custom.py
        run: cp ${{ github.workspace }}/.github/workflows/nightly_custom_windows.py custom.py
      
      - name: Build
        # openvr seems to be a problem child that like to get stuck in CMake on Ubuntu.
        # build it first to avoid it loking up things. libjpeg is another trouble maker.
        run: |
          scons tools=mingw64 -j 1 lib_openvr
          scons tools=mingw64 -j 1 lib_libjpeg
          scons tools=mingw64 -j 14 archive
      
  #    - name: Build Installer
  #      env:
  #        # get at least error information from wine
  #        WINEDEBUG: -all,err+all
  #        # Run virtual X buffer on this port
  #        DISPLAY: :99
  #
  #      run: |
  #        unzip archive/build/dragengine-nightly-windows64.zip -d installer/windows/unpacked
  #        unzip archive/build/dragengine-sdk-nightly-windows64.zip -d installer/windows/unpacked
  #        unzip archive/build/deigde-nightly-windows64.zip -d installer/windows/unpacked
  #        unzip archive/build/deigde-sdk-nightly-windows64.zip -d installer/windows/unpacked
  #        curl -SL "http://files.jrsoftware.org/is/5/innosetup-5.6.1-unicode.exe" -o is.exe
  #        wine-x11-run wine is.exe /SP- /VERYSILENT
  #      
  #    - name: Get current date
  #      id: date
  #      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  #      
  #    - name: Store Artifact
  #      uses: actions/upload-artifact@v2
  #      with:
  #        name: build-windows
  #        path: |
  #          installer/build/install-dragengine-nightly-linux64.sh
  #          installer/build/install-dragengine-dev-nightly-linux64.sh
  #          installer/build/install-deigde-nightly-linux64.sh
  #          installer/build/install-deigde-dev-nightly-linux64.sh
  
  upload:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]
    
    steps:
      - name: Get Linux Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-linux
      
      #- name: Get Windows Artifact
      #  uses: actions/download-artifact@v2
      #  with:
      #    name: build-windows
      
      - name: Upload Artifacts
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'actiontest' #'nightly'
          name: 'Action Test' #'Drag[en]gine Game Engine Release - Nightly Build'
          body: >
            Continuous Nightly Build of the Drag[en]gine Game Engine.
            Created: ${{ steps.date.outputs.date }}
            Changelog: https://dragondreams.ch/?page_id=287
            
            Builds are potentially unstable. Use at own risk.
          prerelease: true
          gzip: false
          allow_override: true
          draft: true
          files: >
            install-dragengine-nightly-linux64.sh
            install-dragengine-dev-nightly-linux64.sh
            install-deigde-nightly-linux64.sh
            install-deigde-dev-nightly-linux64.sh
