name: Nightly Build

on:
  workflow_dispatch:

jobs:
  Build Linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons cmake autoconf libtool nasm \
            patchelf libx11-dev libxrandr-dev libgl-dev libxi-dev libpulse-dev \
            libasound2-dev portaudio19-dev libxft-dev extra-cmake-modules \
            flex bison gettext
      
      - name: Init custom.py
        run: cp ${{ github.workspace }}/.github/workflows/nightly_custom.py custom.py
      
      - name: Build
        run: scons -j 14 archive installer
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Cache Artifact
        uses: actions/cache@v2
        env:
          cache-name: cache-linux
        with:
          path: |
            ${{ github.workspace }}/installer/build/install-dragengine-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-dragengine-dev-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-deigde-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-deigde-dev-nightly-linux64.sh
  
  Upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Linux Artifact
        uses: actions/cache@v2
        env:
          cache-name: cache-linux
        with:
          path: |
            ${{ github.workspace }}/installer/build/install-dragengine-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-dragengine-dev-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-deigde-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-deigde-dev-nightly-linux64.sh
      
      - name: Upload Artifacts
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'nightly'
          name: 'Drag[en]gine Game Engine Release - Nightly Build'
          body: >
            Continuous Nightly Build of the Drag[en]gine Game Engine.
            Created: ${{ steps.date.outputs.date }}
            Changelog: https://dragondreams.ch/?page_id=287
            
            Builds are potentially unstable. Use at own risk.
          prerelease: true
          gzip: false
          allow_override: true
          files: >
            ${{ github.workspace }}/installer/build/install-dragengine-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-dragengine-dev-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-deigde-nightly-linux64.sh
            ${{ github.workspace }}/installer/build/install-deigde-dev-nightly-linux64.sh
