# general configuration
#########################
with_tests = 'yes'
with_warnerrors = 'yes'
with_debug = 'no'
with_verbose = 'no'
with_threads = '14'

# external library configuration
##################################
with_system_zlib = 'no'
with_system_libpng = 'no'
with_system_libapng = 'no'
with_system_libjpeg = 'no'
with_system_openal = 'no'
with_openal_backends = ','.join(['alsa', 'pulseaudio', 'portaudio', 'oss'])
with_system_libogg = 'no'
with_system_libvorbis = 'no'
with_system_libtheora = 'no'
with_system_fox = 'no'
with_system_dragonscript = 'no'
with_system_libffi = 'no'
with_system_libltdl = 'no'
with_system_libsigsegv = 'no'
with_system_smalltalk = 'no'
with_system_libevdev = 'no'
with_system_libusb = 'no'
with_system_libhidapi = 'no'
with_system_libopenhmd = 'no'
with_system_fftw = 'no'
with_opengl = 'yes'
with_python = 'no'
with_npapisdk = 'no'
with_dl = 'no'
with_pthread = 'no'
with_x = 'no'

# modules configuration
#########################
build_audio_openal = 'yes'
build_cr_basic = 'yes'
build_graphics_opengl = 'yes'
build_image_png = 'yes'
build_image_png3d = 'yes'
build_image_jpeg = 'yes'
build_input_x = 'no'
build_input_w32 = 'yes'
build_input_beos = 'no'
build_input_macos = 'no'
build_input_android = 'no'
build_physics_bullet = 'yes'
build_script_ds = 'yes'
build_script_python = 'no'
build_script_smalltalk = 'no'
build_sound_ogg = 'yes'
build_video_theora = 'yes'
build_video_apng = 'yes'
build_igde = 'yes'
build_guilauncher = 'yes'
build_plugin_npapi = 'no'
build_launcher_android = 'no'
build_archive_delga = 'yes'

# archiving
#############
archive_format = 'zip'
archive_name_engine = 'dragengine-nightly-windows64'
archive_name_engine_dev = 'dragengine-sdk-nightly-windows64'
archive_name_igde = 'deigde-nightly-windows64'
archive_name_igde_dev = 'deigde-sdk-nightly-windows64'
archive_name_special = 'despecial-nightly-windows64'
