name: Rebuild MSIX

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: 'X.Y{.Z}'

jobs:
  build_windows:
    uses: ./.github/workflows/build_windows.yml
    with:
      releaseVersion: ${{ github.event.inputs.version }}
      buildVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-windows
  
  build_msix:
    needs: [build_windows]
    uses: ./.github/workflows/build_msix.yml
    with:
      releaseVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-windows
      artifactMsix: msix-windows
