name: Snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        type: string
        default: 'master'
      version:
        description: 'Version'
        required: true
        type: string
        default: 'X.Y{.Z}'
      withLinux:
        description: 'Build Linux'
        required: false
        type: boolean
        default: true
      withLinuxCI:
        description: 'Build Linux CI'
        required: false
        type: boolean
        default: true
      withWindows:
        description: 'Build Windows'
        required: false
        type: boolean
        default: true
      withAndroid:
        description: 'Build Android'
        required: false
        type: boolean
        default: true

jobs:
  validate_version:
    runs-on: ubuntu-latest
    steps:
      - name: Validate version format
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+(\.[0-9]+(\.[0-9]+)?)?$ ]]; then
            echo "Error: Version must be in format X, X.Y or X.Y.Z"
            exit 1
          fi
  
  generate_buildnumbers:
    needs: [validate_version]
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1.0.4
        with:
          token: ${{ secrets.PAT_BUILDBOT }}
          prefix: github
  
  build_linux:
    if: ${{ github.event.inputs.withLinux == 'true' }}
    needs: [generate_buildnumbers]
    uses: ./.github/workflows/build_linux.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      buildVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-linux
      artifactInstaller: installers-linux
      artifactTools: tools-crossplatform
      sconscache: false
  
  nightly_checks:
    if: ${{ github.event.inputs.withLinux == 'true' }}
    needs: [build_linux]
    uses: ./.github/workflows/nightly_checks.yml
  
  build_windows:
    if: ${{ github.event.inputs.withWindows == 'true' }}
    needs: [generate_buildnumbers]
    uses: ./.github/workflows/build_windows_vs.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      buildVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-windows
  
  build_windows_installer:
    if: ${{ github.event.inputs.withWindows == 'true' }}
    needs: [build_windows]
    uses: ./.github/workflows/build_windows_installer.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-windows
      artifactInstaller: installers-windows

  build_msix:
    if: ${{ github.event.inputs.withWindows == 'true' }}
    needs: [build_windows]
    uses: ./.github/workflows/build_msix.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-windows
      artifactMsix: msix-windows
  
  build_linux_ci:
    if: ${{ github.event.inputs.withLinuxCI == 'true' }}
    needs: [generate_buildnumbers]
    uses: ./.github/workflows/build_linux_ci.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      buildVersion: ${{ github.event.inputs.version }}
      artifactArchive: archives-linux-ci
      artifactInstaller: installers-linux-ci
      sconscache: false
  
  build_android_armv8:
    if: ${{ github.event.inputs.withAndroid == 'true' }}
    needs: [generate_buildnumbers]
    uses: ./.github/workflows/build_android.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      buildVersion: ${{ github.event.inputs.version }}
      androidArch: 'armv8'
      artifactArchive: archives-android-armv8
      buildNumber: ${{ needs.generate_buildnumbers.outputs.build_number }}
      sconscache: false
  
  build_android_armv7:
    if: ${{ github.event.inputs.withAndroid == 'true' }}
    needs: [generate_buildnumbers]
    uses: ./.github/workflows/build_android.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      buildVersion: ${{ github.event.inputs.version }}
      androidArch: 'armv7'
      artifactArchive: archives-android-armv7
      buildNumber: ${{ needs.generate_buildnumbers.outputs.build_number }}
      sconscache: false
  
  build_live:
    if: ${{ github.event.inputs.withLinux == 'true' && github.event.inputs.withWindows == 'true' }}
    needs: [build_linux, build_windows]
    uses: ./.github/workflows/build_live.yml
    with:
      releaseVersion: ${{ github.event.inputs.version }}
      artifactLinux: archives-linux
      artifactWindows: archives-windows
      artifactLauncher: archive-livelauncher
    
  build_testing:
    if: ${{ github.event.inputs.withLinuxCI == 'true' }}
    needs: [build_linux_ci]
    uses: ./.github/workflows/build_testing.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      artifactInstallerCI: installers-linux-ci
      artifactTesting: archive-testing
    
  testing:
    if: ${{ github.event.inputs.withLinux == 'true' && github.event.inputs.withLinuxCI == 'true' }}
    needs: [build_linux, build_testing]
    uses: ./.github/workflows/testing.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.version }}
      artifactArchive: installers-linux
      artifactTesting: archive-testing
      artifactResults: testing-results
