name: Test Build

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons cmake autoconf libtool nasm \
            patchelf libx11-dev libxrandr-dev libgl-dev libxi-dev libpulse-dev \
            libasound2-dev portaudio19-dev libxft-dev extra-cmake-modules \
            flex bison gettext mingw-w64
      
      - name: Init custom.py
        run: cp ${{ github.workspace }}/.github/workflows/nightly_custom_windows.py custom.py
      
      - name: Build
        run: |
          scons tools=mingw64 -j 1 lib_openxr
          scons tools=mingw64 -j 1 lib_openvr
          scons tools=mingw64 -j 1 lib_libjpeg
          scons tools=mingw64 -j 14 archive
          
      - name: Store Archives
        uses: actions/upload-artifact@v2
        with:
          name: archives-windows
          path: |
            archive/build/dragengine-nightly-windows64.zip
            archive/build/dragengine-sdk-nightly-windows64.zip
            archive/build/deigde-nightly-windows64.zip
            archive/build/deigde-sdk-nightly-windows64.zip
  
  build_windows_installer:
    runs-on: ubuntu-latest
    needs: [build_windows]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Get Windows Archives
        uses: actions/download-artifact@v2
        with:
          name: archives-windows
      
      - name: Unpack Windows Archives
        run: |
          sudo apt-get install -y unzip
          unzip archive/build/dragengine-nightly-windows64.zip -d installer/windows/unpacked 
          unzip archive/build/dragengine-sdk-nightly-windows64.zip -d installer/windows/unpacked
          unzip archive/build/deigde-nightly-windows64.zip -d installer/windows/unpacked
          unzip archive/build/deigde-sdk-nightly-windows64.zip -d installer/windows/unpacked
      
      - name: Fix GitHub problems with wine32
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update -qq
          sudo apt-get install -yqq --allow-downgrades libpcre2-8-0/focal libpcre2-16-0/focal libpcre2-32-0/focal libpcre2-posix2/focal
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          
      - name: Install required packages X11Client
        # see https://github.com/amake/x11client/blob/master/Dockerfile
        run: |
          export DISPLAY=xserver:0
          sudo xauth merge /Xauthority/xserver.xauth
          
      - name: Install required packages Wine32
        # see https://github.com/amake/wine/blob/master/Dockerfile
        run: |
          sudo apt-get install -yqq wine-stable
          export WINE_MONO_VERSION=4.9.4
          sudo curl -SL 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' -o /usr/local/bin/winetricks
          sudo chmod +x /usr/local/bin/winetricks
          sudo mkdir -p /usr/share/wine/mono
          sudo curl -SL 'https://sourceforge.net/projects/wine/files/Wine%20Mono/$WINE_MONO_VERSION/wine-mono-$WINE_MONO_VERSION.msi/download' -o /usr/share/wine/mono/wine-mono-$WINE_MONO_VERSION.msi
          sudo chmod +x /usr/share/wine/mono/wine-mono-$WINE_MONO_VERSION.msi
          
      - name: Prepare for running wine
        # see https://github.com/amake/wine/blob/master/Dockerfile
        run: |
          export WINEPREFIX=/home/runner/.wine
          export WINEARCH=win32
          export WINEDEBUG="-all,err+all"
          export DISPLAY=:99
          sudo cp -af ${{ github.workspace }}/.github/workflows/wine_opt_bin/* /usr/bin
          
      - name: Install InnoSetup
        run: |
          curl -SL "http://files.jrsoftware.org/is/5/innosetup-5.6.1-unicode.exe" -o is.exe
          wine-x11-run wine is.exe /SP- /VERYSILENT
          cd "/home/runner/.wine/drive_c/Program Files/Inno Setup 5/Languages"
          curl -L "https://api.github.com/repos/jrsoftware/issrc/tarball/29b1e8e8ebe7cf96ca854a1d6be2ae7af7f8018d" | tar xz --strip-components=4 --wildcards "*/Files/Languages/Unofficial/*.isl"
      
      - name: Update ISS files
        run: |
          cd ${{ github.workspace }}/installer/windows
          sed -e "s/%VERSION%/nightly/g" dragengine64.iss.in >dragengine64.iss
          sed -e "s/%VERSION%/nightly/g" dragengine64-sdk.iss.in >dragengine64-sdk.iss
          sed -e "s/%VERSION%/nightly/g" deigde64.iss.in >deigde64.iss
          sed -e "s/%VERSION%/nightly/g" deigde64-sdk.iss.in >deigde64-sdk.iss
      
      - name: Build Installers
        run: |
          wine-x11-run iscc dragengine64.iss
          wine-x11-run iscc dragengine64-sdk.iss
          wine-x11-run iscc deigde64.iss
          wine-x11-run iscc deigde64-sdk.iss
