name: Test Build

on:
  workflow_dispatch:

jobs:
  build_windows_installer:
    runs-on: ubuntu-latest
    
    container:
      image: amake/innosetup
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: |
          cd /github/workspace/installer/windows
          sed -e "s/%VERSION%/nightly/g" dragengine64.iss.in >dragengine64.iss
          sed -e "s/%VERSION%/nightly/g" dragengine64-sdk.iss.in >dragengine64-sdk.iss
          sed -e "s/%VERSION%/nightly/g" deigde64.iss.in >deigde64.iss
          sed -e "s/%VERSION%/nightly/g" deigde64-sdk.iss.in >deigde64-sdk.iss
          iscc dragengine64.iss
          iscc dragengine64-sdk.iss
          iscc deigde64.iss
          iscc deigde64-sdk.iss
