name: Test Build

on:
  workflow_dispatch:

jobs:
  build_windows_installer:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt-get install -y --no-install-recommends xauth curl unzip ca-certificates wine wine32 procps xvfb
          sudo curl -SL 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' -o /usr/local/bin/winetricks
          sudo chmod +x /usr/local/bin/winetricks
          sudo mkdir -p /usr/share/wine/mono
          sudo curl -SL 'https://sourceforge.net/projects/wine/files/Wine%20Mono/$WINE_MONO_VERSION/wine-mono-$WINE_MONO_VERSION.msi/download' -o /usr/share/wine/mono/wine-mono-$WINE_MONO_VERSION.msi
          sudo chmod +x /usr/share/wine/mono/wine-mono-$WINE_MONO_VERSION.msi
          export WINEARCH win32
          export WINEDEBUG="-all,err+all"
          export DISPLAY=:99
          sudo cp -af ${{ github.workspace }}/.github/workflows/wine_opt_bin/* /usr/bin
          curl -SL "http://files.jrsoftware.org/is/5/innosetup-5.6.1-unicode.exe" -o is.exe
          wine-x11-run wine is.exe /SP- /VERYSILENT
          cd "~/.wine/drive_c/Program Files/Inno Setup 5/Languages"
          curl -L "https://api.github.com/repos/jrsoftware/issrc/tarball/29b1e8e8ebe7cf96ca854a1d6be2ae7af7f8018d" | tar xz --strip-components=4 --wildcards "*/Files/Languages/Unofficial/*.isl"
      
      - name: Build
        run: |
          cd /github/workspace/installer/windows
          sed -e "s/%VERSION%/nightly/g" dragengine64.iss.in >dragengine64.iss
          sed -e "s/%VERSION%/nightly/g" dragengine64-sdk.iss.in >dragengine64-sdk.iss
          sed -e "s/%VERSION%/nightly/g" deigde64.iss.in >deigde64.iss
          sed -e "s/%VERSION%/nightly/g" deigde64-sdk.iss.in >deigde64-sdk.iss
          wine-x11-run iscc dragengine64.iss
          wine-x11-run iscc dragengine64-sdk.iss
          wine-x11-run iscc deigde64.iss
          wine-x11-run iscc deigde64-sdk.iss
