/*
 * MIT License
 *
 * Copyright (C) 2024, DragonDreams GmbH (info@dragondreams.ch)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef _DEMODELTEXTURE_H_
#define _DEMODELTEXTURE_H_

#include "../../common/string/decString.h"


/**
 * \brief Model texture.
 * 
 * Faces viewn from the back side are invisible. If double-sided is set
 * back faces are also rendered as if they are front faces. This can be
 * used for thin geometry represented by a single face. THe same is true
 * for shadow casting. Back faces do not cast shadows unless double-sided
 * is set.
 * 
 * If faces are set to be rendered as decals they are rendered similar to
 * how deDecal are rendered with the difference they are not generated by
 * projecting a quadrilateral onto the mesh but using the faces instead.
 * If decal is set the decal offset parameter is used to determine the
 * amount of offset relative to other decal set textures. Larger numbers
 * cover textures with lower decal offset.
 * 
 */
class DE_DLL_EXPORT deModelTexture{
private:
	decString pName;
	int pWidth;
	int pHeight;
	bool pDoubleSided;
	bool pDecal;
	int pDecalOffset;
	
	
	
public:
	/** \name Constructors and Destructors */
	/*@{*/
	/** \brief Create model texture. */
	deModelTexture( const char *name, int width, int height );
	
	/** \brief Clean up model texture. */
	~deModelTexture();
	/*@}*/
	
	
	
	/** \name Management */
	/*@{*/
	/** \brief Name. */
	inline const decString &GetName() const{ return pName; }
	
	/** \brief Width. */
	inline int GetWidth() const{ return pWidth; }
	
	/** \brief Height. */
	inline int GetHeight() const{ return pHeight; }
	
	/** \brief Faces of this texture are double sided. */
	inline bool GetDoubleSided() const{ return pDoubleSided; }
	
	/** \brief Set if faces of this texture are double sided. */
	void SetDoubleSided( bool doubleSided );
	
	/** \brief Faces of this texture are rendered as decals. */
	inline bool GetDecal() const{ return pDecal; }
	
	/** \brief Set if faces of this texture are rendered as decals. */
	void SetDecal( bool decal );
	
	/** \brief Decal offset. */
	inline int GetDecalOffset() const{ return pDecalOffset; }
	
	/** \brief Set decal offset. */
	void SetDecalOffset( int offset );
	/*@}*/
};

#endif
