#!/bin/sh

set -eu

escone() {
    printf %s\\n "$1" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"
}

winpaths() {
    for arg; do
        if [ -e "$arg" ]; then
            escone "$(winepath -w "$arg")"
        else
            escone "$arg"
        fi
    done
    echo " "
}

winenv() {
    wine cmd /c "echo $1" | tr -d '\r'
}

PROGFILES_PATH="$(winepath -u "$(winenv %PROGRAMFILES%)")"

INNO_BIN="Inno Setup 5/ISCC.exe"
INNO_PATH="${PROGFILES_PATH}/${INNO_BIN}"

eval set -- "$(winpaths "$@")"

exec wine "$INNO_PATH" "$@"
